#!/bin/bash

#Jamf Log Grabber but make it just for Jamf Connect


#define variables
log_folder=~/Desktop/Logs
not_found=~/Desktop/Logs/Results/
results=$not_found/Results.txt
connect=$log_folder/Connect
currenttime=$(date +"%D %T")

#clear out previous results
if [ -e $log_folder ] ;then rm -r $log_folder
fi

#create a folder to save all logs
mkdir -p $log_folder/{Results,Connect,}

#create a log file for script and save to Not_Found directory so users can see what logs were not gathered
touch $results
echo "Jamf Connect Log Grabber ran on $currenttime" >>$results

#check for jamf login logs and plist, copy, and convert to readable format
if [ -e /tmp/jamf_login.log ]; then cp "/tmp/jamf_login.log" $connect
else
	echo "Jamf Login /tmp file not found" >> $results
fi

if [ -e /Library/Managed\ Preferences/com.jamf.connect.login.plist ]; then cp "/Library/Managed Preferences/com.jamf.connect.login.plist" "$connect/com.jamf.connect.login_managed.plist" | plutil -convert xml1 "$connect/com.jamf.connect.login_managed.plist" | log show --style compact --predicate 'subsystem == "com.jamf.connect.login"' --debug > "$connect/com.jamf.connect.login.log"
else
	echo "Jamf Connect Login plist not found" >> $results
fi

#check for jamf connect license, copy, decrypt, and convert to readable format
LicensefromLogin=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.login.plist LicenseFile 2>/dev/null)
LicensefromMenubar=$(defaults read /Library/Managed\ Preferences/com.jamf.connect.plist LicenseFile 2>/dev/null)
if [[ "$LicensefromLogin" == "PD94"* ]]; then
	(echo "$LicensefromLogin" | base64 -d) > $connect/license.txt
elif [[ "$LicensefromMenubar" == "PD94"* ]]; then
	(echo "$LicensefromMenubar" | base64 -d) > $connect/license.txt
else
	file=""
fi

#check for jamf connect state plist, copy, and convert to readable format
State_plist=$(defaults read com.jamf.connect.state.plist 2>/dev/null)
if [[ "$State_plist" == "" ]]; then
	echo "A Jamf Connect State list was not found because no user is logged into Menu Bar" >> $results; else cp ~/Library/Preferences/com.jamf.connect.state.plist "$connect/com.jamf.connect.state.plist" | plutil -convert xml1 $connect/com.jamf.connect.state.plist
	fi

#check for jamf connect menu bar plist, copy, and convert to readable format
if [ -e /Library/Managed\ Preferences/com.jamf.connect.plist ]; then cp "/Library/Managed Preferences/com.jamf.connect.plist" "$connect/com.jamf.connect_managed.plist" | plutil -convert xml1 "$connect/com.jamf.connect_managed.plist" | log show --style compact --predicate 'subsystem == "com.jamf.connect"' --debug > "$connect/com.jamf.connect.log"
else
	echo "Jamf Connect plist not found" >> $results
fi

#check for kerberos ticket
kerblist=$("klist" 2>/dev/null)
if [[ "$kerblist" == "" ]];then
	echo "No Kerberos Ticket for Current Logged in User" > $connect/klist_manuallyCollected.txt; else
		echo $kerblist > $connect/klist_manuallyCollected.txt
	fi

#list authchanger settings
/usr/local/bin/authchanger -print > "$connect/authchanger_manuallyCollected.txt"

